python scatterplots_data.py

manim -qh colours.py ColourAxesRGB
manim -qh colours.py ColourDisksRGB
manim -qh colours.py ColourDisksCYM
manim -qh colours.py ColourDisksPaint
manim -qh colours.py ColourTriangle
manim -qh cones.py HSLDisk
manim -qh cones.py HLSCone
manim -qh cones.py HSVCylinder
manim -qh cones.py ColourSpaceNames
manim -qh definitions.py Def1
manim -qh examples.py ExampleText
manim -qh examples.py ExampleTeX
manim -qh examples.py ExampleCode
manim -qh examples.py Example3DSphere
manim -qh examples.py Example3DSaddle1
manim -qh growing_circle.py CircleNegative
manim -qh growing_circle.py CirclePositive
manim -qh growing_circle.py CircleFlat
manim -qh growing_circle.py CurvaturePositive
manim -qh growing_circle.py CurvatureNegative
manim -qh growing_circle.py Flat1
manim -qh growing_circle.py Flat2
manim -qh growing_circle.py Hyperboloid
manim -qh growing_circle.py Saddle
manim -qh growing_circle.py SurfaceExamples
manim -qh growing_circle.py CurvatureExamples
manim -qh Problem.py Example
manim -qh scatterplots.py Mnist
manim -qh statistical_manifolds.py GaussianFormula
manim -qh statistical_manifolds.py GaussianDistribution
manim -qh statistical_manifolds.py GaussianPlane
manim -qh statistical_manifolds.py GaussianPlane2
manim -qh statistical_manifolds.py GaussianPlane3
manim -qh statistical_manifolds.py DistancesDifferent
manim -qh titles_Bitter.py Title0
manim -qh titles_Bitter.py Title1
manim -qh titles_Bitter.py Title2
manim -qh titles_Bitter.py Title3
manim -qh titles_Bitter.py TitleN
manim -qh titles_Bitter.py TitleRef
manim -qh titles_Bitter.py TitleDef
manim -qh trees.py Tree
manim -qh trees.py Circles
manim -qh trees.py MST
manim -qh trees.py PoincareDisk
manim -qh trees.py PoincareHalfPlane
manim -qh trees.py PoincareHalfPlane2
